default:
  NAME: vAlert
  HOST: 0.0.0.0
  PORT: 8000

  POSTGRES:
    host: postgres
    port: 5432
    user: postgres
    password: postgres
    database: valert
    
  RABBIT:
    host: rabbitmq
    port: 5672
    user: guest
    password: guest

  LOGGING_BASE_CONFIG:
    version: 1
    disable_existing_loggers: false
    formatters:
      default:
        format: "%(levelname)-8s# %(filename)s[LINE:%(lineno)d] [%(asctime)s.%(msecs)d]:  %(message)s"
    handlers:
      console:
        level: DEBUG
        class: logging.StreamHandler
        formatter: default
        stream: ext://sys.stdout
      error:
        level: ERROR
        class: logging.StreamHandler
        formatter: default
        stream: ext://sys.stderr
    loggers:
      default:
        level: DEBUG
        handlers: [ console, error ]
    root:
      level: INFO
      handlers: [ console, error ]
